export const IMAGE_PATHS = {
  technologies: {
    apollo: "/img/techImages/apollo.png",
    babel: "/img/techImages/babel.png",
    css3: "/img/techImages/css3.png",
    cypress: "/img/techImages/cypress.png",
    eslint: "/img/techImages/eslint.png",
    expo: "/img/techImages/expo.png",
    figma: "/img/techImages/figma.png",
    git: "/img/techImages/git.png",
    graphql: "/img/techImages/graphql.png",
    gulp: "/img/techImages/gulp.png",
    html5: "/img/techImages/html5.png",
    illustrator: "/img/techImages/illustrator.png",
    javascript: "/img/techImages/javascript.png",
    jest: "/img/techImages/jest.png",
    jquery: "/img/techImages/jquery.png",
    materialUi: "/img/techImages/materialUi.png",
    nextjs: "/img/techImages/nextjs.png",
    photoshop: "/img/techImages/photoshop.png",
    prettier: "/img/techImages/prettier.png",
    react: "/img/techImages/react.png",
    reactNative: "/img/techImages/reactNative.png",
    redux: "/img/techImages/redux.png",
    sass: "/img/techImages/sass.png",
    storybook: "/img/techImages/storybook.png",
    styledComponents: "/img/techImages/styledComponents.png",
    testingLibrary: "/img/techImages/testingLibrary.png",
    typescript: "/img/techImages/typescript.png",
    vite: "/img/techImages/vite.png",
    webpack: "/img/techImages/webpack.png",
    noImage: "/img/techImages/noImage.png",
  },
} as const
