import { ThemeProvider, createGlobalStyle } from "styled-components"
import { theme } from "@/styles/theme"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "./globals.css"
import { globalStyle } from "@/styles/globalStyle"

const inter = Inter({ subsets: ["latin"] })

const GlobalStyle = createGlobalStyle`
  ${globalStyle}
`

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <GlobalStyle />
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </html>
  )
}
